# Importing the libraries

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset

In [5]:
df = pd.read_csv('https://github.com/YBI-Foundation/Dataset/raw/main/Diabetes.csv')

# Get Information of Dataframe


In [6]:
df.info()   #gives column name, count,  not null category, D-type(data type)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   pregnancies  768 non-null    int64  
 1   glucose      768 non-null    int64  
 2   diastolic    768 non-null    int64  
 3   triceps      768 non-null    int64  
 4   insulin      768 non-null    int64  
 5   bmi          768 non-null    float64
 6   dpf          768 non-null    float64
 7   age          768 non-null    int64  
 8   diabetes     768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [7]:
df.describe()   #gives the linear relation of each column with another column

pregnancies     glucose   diastolic     triceps     insulin  \
count   768.000000  768.000000  768.000000  768.000000  768.000000   
mean      3.845052  120.894531   69.105469   20.536458   79.799479   
std       3.369578   31.972618   19.355807   15.952218  115.244002   
min       0.000000    0.000000    0.000000    0.000000    0.000000   
25%       1.000000   99.000000   62.000000    0.000000    0.000000   
50%       3.000000  117.000000   72.000000   23.000000   30.500000   
75%       6.000000  140.250000   80.000000   32.000000  127.250000   
max      17.000000  199.000000  122.000000   99.000000  846.000000   

              bmi         dpf         age    diabetes  
count  768.000000  768.000000  768.000000  768.000000  
mean    31.992578    0.471876   33.240885    0.348958  
std      7.884160    0.331329   11.760232    0.476951  
min      0.000000    0.078000   21.000000    0.000000  
25%     27.300000    0.243750   24.000000    0.000000  
50%     32.000000    0.372500   29.000000    0.000000  
75%     36.600000    0.626250   41.000000    1.000000  
max     67.100000    2.420000   81.000000    1.000000

In [8]:
df.head()

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
0            6      148         72       35        0  33.6  0.627   50   
1            1       85         66       29        0  26.6  0.351   31   
2            8      183         64        0        0  23.3  0.672   32   
3            1       89         66       23       94  28.1  0.167   21   
4            0      137         40       35      168  43.1  2.288   33   

   diabetes  
0         1  
1         0  
2         1  
3         0  
4         1

In [9]:
df.isnull().sum() #(df.isna().sum() gives same result)
#gives the sum of all null values columns-wise

pregnancies    0
glucose        0
diastolic      0
triceps        0
insulin        0
bmi            0
dpf            0
age            0
diabetes       0
dtype: int64

In [10]:
df.nunique()   #gives total no. of unique entries 

pregnancies     17
glucose        136
diastolic       47
triceps         51
insulin        186
bmi            248
dpf            517
age             52
diabetes         2
dtype: int64

In [11]:
df.columns  #give column names in the dataframe

Index(['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age', 'diabetes'],
      dtype='object')

In [12]:
df.shape

(768, 9)

In [13]:
df['diabetes'].value_counts()

0    500
1    268
Name: diabetes, dtype: int64

In [14]:
df.groupby('diabetes').mean()

pregnancies     glucose  diastolic    triceps     insulin  \
diabetes                                                              
0            3.298000  109.980000  68.184000  19.664000   68.792000   
1            4.865672  141.257463  70.824627  22.164179  100.335821   

                bmi       dpf        age  
diabetes                                  
0         30.304200  0.429734  31.190000  
1         35.142537  0.550500  37.067164

# Setting X and y

In [15]:
X= df.drop('diabetes',axis=1).values

In [16]:
y=df['diabetes'].values

In [17]:
X.shape,y.shape

((768, 8), (768,))

#Standardization

In [18]:
from sklearn.preprocessing import MinMaxScaler

In [19]:
mn= MinMaxScaler()

In [20]:
X=mn.fit_transform(X)

In [21]:
X

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

# Train Test Split

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.3,stratify=y,random_state=2323)

In [24]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((537, 8), (231, 8), (537,), (231,))

# Get Model Test 

In [25]:
from sklearn.linear_model import LogisticRegression

In [26]:
lr= LogisticRegression()

In [27]:
lr.fit(X_train, y_train)

LogisticRegression()

# Get Model Prediction

In [28]:
y_pred= lr.predict(X_test)

In [29]:
y_pred.shape

(231,)

In [30]:
y_pred

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1])

# Get Probability of Each Predicttted Class

In [31]:
lr.predict_proba(X_test)

array([[0.75404448, 0.24595552],
       [0.58011549, 0.41988451],
       [0.83087557, 0.16912443],
       [0.44991098, 0.55008902],
       [0.24067598, 0.75932402],
       [0.57446319, 0.42553681],
       [0.77914603, 0.22085397],
       [0.78824961, 0.21175039],
       [0.82014912, 0.17985088],
       [0.40766871, 0.59233129],
       [0.84173513, 0.15826487],
       [0.71011999, 0.28988001],
       [0.35276382, 0.64723618],
       [0.54258389, 0.45741611],
       [0.62175918, 0.37824082],
       [0.48752947, 0.51247053],
       [0.85285985, 0.14714015],
       [0.73075664, 0.26924336],
       [0.42678927, 0.57321073],
       [0.87555195, 0.12444805],
       [0.93145641, 0.06854359],
       [0.78211464, 0.21788536],
       [0.81093474, 0.18906526],
       [0.52652421, 0.47347579],
       [0.24033188, 0.75966812],
       [0.3754181 , 0.6245819 ],
       [0.28492561, 0.71507439],
       [0.75048549, 0.24951451],
       [0.78618566, 0.21381434],
       [0.58885993, 0.41114007],
       [0.

# Get Model Evaluation

In [32]:
from sklearn.metrics import confusion_matrix, classification_report

In [33]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.78      0.95      0.86       150
           1       0.84      0.51      0.63        81

    accuracy                           0.79       231
   macro avg       0.81      0.73      0.74       231
weighted avg       0.80      0.79      0.78       231



#Get Fututre Predictions 

In [34]:
X_new= df.sample(1)

In [36]:
X_new

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
15            7      100          0        0        0  30.0  0.484   32   

    diabetes  
15         1

In [38]:
X_new.shape

(1, 9)

In [40]:
X_new=X_new.drop('diabetes',axis=1)

In [41]:
X_new

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age
15            7      100          0        0        0  30.0  0.484   32

In [42]:
X_new.shape

(1, 8)

In [43]:
X_new= mn.fit_transform(X_new)

In [44]:
y_pred_new= lr.predict(X_new)

In [46]:
y_pred_new

array([0])

In [47]:
lr.predict_proba(X_new)

array([[0.9918974, 0.0081026]])